### ISSUE TITLE
how to use styled-component 

### ISSUE THREAD

**Issue by gmchaturvedi1** [reactql/kit#106]
hi 
 i am new to this. can u suggest how to use styled-component in this .

Reagrds
gmchaturvedi

**Comment by leebenson** [comment]
If you're talking about the [styled-components](https://github.com/styled-components/styled-components) package, there's no special provisions to need to make to a ReactQL project - just import it and use.

If you mean something else, please be more specific.

**Comment by codeandgraphics** [comment]
Hi! 
styled-components works at http://localhost:8080, but if I use SSR, at http://localhost:8081 got error: 
```Warning: Prop `className` did not match. Server: "header__StyledH1-q4sydt-0 eHXSDZ" Client: "sc-bdVaJa rOCEJ"```
and nothing styled. I suppose it need special provisions to SSR part

**Comment by gihrig** [comment]
There's discussion around styled components and SSR [here](https://github.com/styled-components/styled-components/issues/386).

It looks pretty complex... 😦 

SSR is addressed in SC [docs](https://www.styled-components.com/docs/advanced#server-side-rendering). Maybe that will provide answers.

**Comment by leebenson** [comment]
re-opening - there might be cause to add this to `kit/entry/server.js` officially.

**Comment by codeandgraphics** [comment]
For me, it's looks like 
```js
// #line 164 kit/entry/server.js
    const sheet = new ServerStyleSheet();

    // Generate the HTML from our React tree.  We're wrapping the result
    // in `react-router`'s <StaticRouter> which will pull out URL info and
    // store it in our empty `route` object
    const components = (
      <StaticRouter location={ctx.request.url} context={routeContext}>
        <ApolloProvider store={ctx.store} client={ctx.apollo}>
          <StyleSheetManager sheet={sheet.instance}>
            <App />
          </StyleSheetManager>
        </ApolloProvider>
      </StaticRouter>
    );
```

```js
// #line 221 kit/entry/server.js
const reactStream = ReactDOMServer.renderToNodeStream(
      <Html
        head={Helmet.rewind()}
        window={{
          webpackManifest: chunkManifest,
          __STATE__: ctx.store.getState(),
        }}
        css={css}
        styles={sheet.getStyleElement()}
        scripts={scripts}>
        {components}
      </Html>,
    );
```

Then I passed `styles` to `kit/views/ssr.js`
```js
const Html = ({ head, scripts, window, css, styles, children }) => (
  <html lang="en" prefix="og: http://ogp.me/ns#">
    <head>
      <meta charSet="utf-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta httpEquiv="Content-Language" content="en" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      {head.meta.toComponent()}
      <link rel="stylesheet" href={css} />
      {head.title.toComponent()}
      {styles}
    </head>
    <body>
      <div id="main">{children}</div>
      <script
        dangerouslySetInnerHTML={{
          __html: Object.keys(window).reduce(
            (out, key) => out += `window.${key}=${JSON.stringify(window[key])};`,
            ''),
        }} />
      {scripts.map(src => <script key={src} src={src} />)}
    </body>
  </html>
);
```

It works, but still shows warning `Warning: Prop `className` did not match. Server: "header__StyledH1-q4sydt-0 eHXSDZ" Client: "sc-bdVaJa rOCEJ"`, because styled-components from client binds too

**Comment by leebenson** [comment]
Apologies for the generic response, but I've released a new [v3.0 kit](https://github.com/leebenson/reactql/releases/tag/3.0.0), which has been re-written from the ground up.

It bumps the ReactQL stack to Webpack 4, React 16.4, Apollo Client 2.0, and adds Styled Components, full SSR (even in development), and has been re-written in Typescript. It's leaner, faster and has been brought completely up-to-date.

If you're still using ReactQL (and I appreciate you may not be, given the time lag in my response), I'd recommend checking out the new kit to see if your issue has been answered. If not, please feel free to post a new issue at https://github.com/leebenson/reactql
